version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    allow:
      - dependency-type: "all"
    versioning-strategy: lockfile-only
    open-pull-requests-limit: 99
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️ [dev]"
