version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: weekly
    groups:
      ci:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: weekly
    groups:
      docs:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    allow:
      - dependency-type: "all"
    versioning-strategy: lockfile-only
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️ [dev]"
    groups:
      lockfile-dev:
        dependency-type: "development"
      lockfile-runtime:
        dependency-type: "production"
